version: "3.9"

services:
  server:
    container_name: "festapi_server"
    image: "festapi_server"
    build:
      context: .
      target: ${TARGET}
    environment:
      - COMPOSE_PROJECT_NAME=${PROJECT_NAME}
    ports:
      - ${SERVER_PORT}:8000
    volumes:
      - .:/app
      - ./logs:/logs # Volume map logs in PROD
    depends_on:
      - db

  db:
    container_name: "festapi_db"
    image: "postgres:14-alpine"
    ports:
      - ${POSTGRES_PORT}:5432
    env_file:
      - .env
    volumes:
      - ${POSTGRES_DATA}:/var/lib/postgresql/data

  adminer:
    container_name: "festapi_adminer"
    image: "adminer"
    ports:
      - ${ADMINER_PORT}:8080
    depends_on:
      - db
    env_file:
      - .env

networks:
  default:
    name: ${PROJECT_NAME}_network
    external: true
