package main

import (
	"github.com/delta/FestAPI/config"
	"github.com/delta/FestAPI/router"
	"github.com/delta/FestAPI/utils"

	"github.com/labstack/echo/v4"
	"github.com/labstack/echo/v4/middleware"

	_ "github.com/delta/FestAPI/docs" // docs is generated by Swag CLI, you have to import it.
)

// @title FestAPI v2
// @version 1.0
// @description API Server for all fests

// @contact.name API Support
// @contact.url http://www.swagger.io/support
// @contact.email support@swagger.io

// @license.name MIT
// @license.url https://opensource.org/licenses/MIT

// @host localhost:8000
// @BasePath /
// @query.collection.format multi
func main() {

	server := echo.New()
	server.Use(middleware.CORS())
	server.Use(middleware.Recover())

	config.InitConfig()
	config.ConnectDB()
	config.MigrateDB()

	router.NewRouter(server)

	utils.InitLogger(server)

	server.Logger.Fatal(server.Start(":" + config.ServerPort))

}
